# Site settings
title: WMTU 91.9 FM Houghton
email: wmtu@mtu.edu
description: > # this means to ignore newlines until "baseurl:"
  WMTU is funded by the Undergraduate Student Government of Michigan Technological University.
  WMTU's bandwidth provided by Resnet
  Â© WMTU 91.9FM Houghton | Michigan Technological University 2015
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://wmtu.mtu.edu" # the base hostname & protocol for your site
twitter_username: WMTU
github_username:  WMTU
office_phone: 906-487-2333
request_line: 906-487-1600
address: > # this means to ignore newlines
  G03W Wadsworth Hall
  1703 Townsend Drive
  Houghton, MI  49931

# Build settings
markdown: kramdown

# WMTU Settings
stream_url: http://54.86.47.36:8000/listen
stream_playlist: http://54.86.47.36:8000/listen.m3u

exclude: [README.md, Gemfile, Gemfile.lock, scripts, bower_components/soundmanager/demo, bower_components/jquery/src]
